### ISSUE TITLE
Pip installation not working(?)

### ISSUE THREAD

**Issue by jtheligand** [open-reaction-database/ord-schema#712] opened 2024-02-19 21:01 UTC
Tried to install using pip install. This seemed to work fine, but was unable to generate a reaction due to ValueError

Was trying to use with Python 3.9.18 but not seeing any errors in the console, etc until I tried to generate a new reaction.

Cloning the git (with Brandon's help!) was able to get working upon python update.

**Comment by bdeadman** [comment] 2024-02-19 23:38
I'm meeting Jessica and Brandon later this week so we can have a quick chat about it then, and work out what guidance/fix is needed. I also have access to the repo they are working in, and the script was fine. The problem appears to be in the ord-schema installation method.

**Comment by bdeadman** [comment] 2024-02-19 23:39
From Brandon:

I can't remember which approach I initially took (i might have tried originally with pip install ord-schema). But the approach I found that worked 100% of the time was to clone from git, cd to the cloned dir and compile directly using pip install -e . Also recall only realizing it needed python 3.10 when I did this outside of the jupyter environment. When I tried to include the cloning aspect directly in the jupyter python environment (including the import of protobuff) I got the same exact errors Jessica is reporting. if the schema is directly installed in the pwd/environment, you can directly call on it and its components without with cloning from git in the src

**Comment by FanwangM** [comment] 2024-02-20 03:27
I think this can trace back to https://github.com/open-reaction-database/ord-schema/blob/1fb700857f56f02edd0348d1c763c16df56db806/setup.py#L35, where the `ord-schema` intended to support Python version > 3.10. But if you want to install it for a Python version lower than 3.10, cloning the code and commenting on this line to lose the constraint should work.

**Comment by FanwangM** [comment] 2024-02-26 17:37
Given that the problem is traced to the Python version requirement in `setup.py`, I will close it. But please feel free to reopen it if you have any other questions. @jtheligand

**Closed by FanwangM** 2024-02-26 17:37 UTC
Labels: bug
